[book]
authors = ["Hadrien Grasland"]
language = "en"
multilingual = false
src = "src"
title = "Code that counts"

[build]
extra-watch-dirs = ["counter/src", "counter/benches"]

[rust]
edition = "2021"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/HadrienG2/code-that-counts"
edit-url-template = "https://github.com/HadrienG2/code-that-counts/edit/master/{path}"
